name: NC-ToteProject

on:
  push:
    branches:
      - ci-cd-gitactions

jobs:
  run-tests:
    #if: false # this will cause the job to be skipped - delete to enable 
    name: run-tests
    runs-on: ubuntu-latest
    # implement me
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Requirements
        run: make requirements
      - name: Dev Setup
        run: make dev-setup
      - name: Run Checks
        run: make run-checks