# Running the security checks using bandit, code check using black, and coverage using unit tests. 
# Trigers whenever there's a push to main of the repository. 

name: NC-ToteProject
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Requirements
        run: make requirements
      - name: Dev Setup
        run: make dev-setup
      - name: Run Checks
        run: make run-checks
